### ISSUE TITLE
both CLIC and CLINT seems to be used for the same thing

### ISSUE THREAD

**Issue by kaddkaka** [riscv/riscv-platform-specs#46]
Two abbreviations seem to be used for "Core-Local Interrupt Controller"

CLINT is the only one mentioned in the Terminology table at the top here: https://github.com/riscv/riscv-platform-specs/blob/main/riscv-platform-spec.adoc#terminology

The specifications linked are:
 - CLIC: https://github.com/riscv/riscv-fast-interrupt/blob/master/clic.adoc
 - ACLINT: https://github.com/riscv/riscv-aclint/releases/download/v1.0-draft2/riscv-aclint-1.0-draft2.pdf

Can/Should this be made more cohesive? `CLIC` seems more in line with `PLIC`.

**Comment by atishp04** [comment]
No. CLIC is not inline with PLIC apart from the name. CLIC is aimed for microcontroller class systems. That's why, it is an option for M platform.
ACLINT provides the local interrupts that high end systems capable of running Rich OS i.e. Linux require.
Timer, IPI (both S-mode & M-mode).

That's why, ACLINT is an option in OS-A platform but not in M platform

**Comment by kumarsankaran** [comment]
Can we close this issue or is there anything else to discuss on this topic?

**Comment by kaddkaka** [comment]
Ok thanks. What is the difference between `ACLINT` and `CLINT`?

It can probably be closed (it might just be confusing for me) ...

**Comment by kumarsankaran** [comment]
The difference between ACLINT and CLINT is described in Section 1 Introduction of the ACLINT spec here https://github.com/riscv/riscv-aclint/blob/main/riscv-aclint.adoc.
I am closing this PR. Please reopen if there are still more questions.
